image: gitpod/workspace-full

tasks:
  - name: Setup and Run
    init: |
      git remote add upstream https://github.com/Skateside/pocket-grimoire.git
      git fetch upstream pull/136/head:pr-136
      git checkout pr-136
      yarn install
    command: yarn dev-server --host 0.0.0.0

ports:
  - port: 8080
    onOpen: open-preview
    visibility: public
